package com.JIAT.seckillDemo.mapper;

import com.JIAT.seckillDemo.pojo.SeckillGoods;
import com.JIAT.seckillDemo.pojo.SeckillGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    long countByExample(SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int deleteByExample(SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int insert(SeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int insertSelective(SeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    List<SeckillGoods> selectByExample(SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    SeckillGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") SeckillGoods record, @Param("example") SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int updateByExample(@Param("record") SeckillGoods record, @Param("example") SeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int updateByPrimaryKeySelective(SeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    int updateByPrimaryKey(SeckillGoods record);
}