package com.JIAT.seckillDemo.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SeckillOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public SeckillOrderExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSeckillIdIsNull() {
            addCriterion("seckill_id is null");
            return (Criteria) this;
        }

        public Criteria andSeckillIdIsNotNull() {
            addCriterion("seckill_id is not null");
            return (Criteria) this;
        }

        public Criteria andSeckillIdEqualTo(Long value) {
            addCriterion("seckill_id =", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdNotEqualTo(Long value) {
            addCriterion("seckill_id <>", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdGreaterThan(Long value) {
            addCriterion("seckill_id >", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdGreaterThanOrEqualTo(Long value) {
            addCriterion("seckill_id >=", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdLessThan(Long value) {
            addCriterion("seckill_id <", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdLessThanOrEqualTo(Long value) {
            addCriterion("seckill_id <=", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdIn(List<Long> values) {
            addCriterion("seckill_id in", values, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdNotIn(List<Long> values) {
            addCriterion("seckill_id not in", values, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdBetween(Long value1, Long value2) {
            addCriterion("seckill_id between", value1, value2, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdNotBetween(Long value1, Long value2) {
            addCriterion("seckill_id not between", value1, value2, "seckillId");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(BigDecimal value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(BigDecimal value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(BigDecimal value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(BigDecimal value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<BigDecimal> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<BigDecimal> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andUerIdIsNull() {
            addCriterion("uer_id is null");
            return (Criteria) this;
        }

        public Criteria andUerIdIsNotNull() {
            addCriterion("uer_id is not null");
            return (Criteria) this;
        }

        public Criteria andUerIdEqualTo(String value) {
            addCriterion("uer_id =", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdNotEqualTo(String value) {
            addCriterion("uer_id <>", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdGreaterThan(String value) {
            addCriterion("uer_id >", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdGreaterThanOrEqualTo(String value) {
            addCriterion("uer_id >=", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdLessThan(String value) {
            addCriterion("uer_id <", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdLessThanOrEqualTo(String value) {
            addCriterion("uer_id <=", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdLike(String value) {
            addCriterion("uer_id like", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdNotLike(String value) {
            addCriterion("uer_id not like", value, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdIn(List<String> values) {
            addCriterion("uer_id in", values, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdNotIn(List<String> values) {
            addCriterion("uer_id not in", values, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdBetween(String value1, String value2) {
            addCriterion("uer_id between", value1, value2, "uerId");
            return (Criteria) this;
        }

        public Criteria andUerIdNotBetween(String value1, String value2) {
            addCriterion("uer_id not between", value1, value2, "uerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(String value) {
            addCriterion("seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(String value) {
            addCriterion("seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(String value) {
            addCriterion("seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(String value) {
            addCriterion("seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(String value) {
            addCriterion("seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(String value) {
            addCriterion("seller_id <=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLike(String value) {
            addCriterion("seller_id like", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotLike(String value) {
            addCriterion("seller_id not like", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIn(List<String> values) {
            addCriterion("seller_id in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotIn(List<String> values) {
            addCriterion("seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(String value1, String value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(String value1, String value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("pay_time is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("pay_time is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("pay_time =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("pay_time <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("pay_time >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_time >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("pay_time <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("pay_time <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<Date> values) {
            addCriterion("pay_time in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<Date> values) {
            addCriterion("pay_time not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("pay_time between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("pay_time not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressIsNull() {
            addCriterion("recevier_address is null");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressIsNotNull() {
            addCriterion("recevier_address is not null");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressEqualTo(String value) {
            addCriterion("recevier_address =", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressNotEqualTo(String value) {
            addCriterion("recevier_address <>", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressGreaterThan(String value) {
            addCriterion("recevier_address >", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressGreaterThanOrEqualTo(String value) {
            addCriterion("recevier_address >=", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressLessThan(String value) {
            addCriterion("recevier_address <", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressLessThanOrEqualTo(String value) {
            addCriterion("recevier_address <=", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressLike(String value) {
            addCriterion("recevier_address like", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressNotLike(String value) {
            addCriterion("recevier_address not like", value, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressIn(List<String> values) {
            addCriterion("recevier_address in", values, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressNotIn(List<String> values) {
            addCriterion("recevier_address not in", values, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressBetween(String value1, String value2) {
            addCriterion("recevier_address between", value1, value2, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierAddressNotBetween(String value1, String value2) {
            addCriterion("recevier_address not between", value1, value2, "recevierAddress");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileIsNull() {
            addCriterion("recevier_mobile is null");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileIsNotNull() {
            addCriterion("recevier_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileEqualTo(String value) {
            addCriterion("recevier_mobile =", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileNotEqualTo(String value) {
            addCriterion("recevier_mobile <>", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileGreaterThan(String value) {
            addCriterion("recevier_mobile >", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileGreaterThanOrEqualTo(String value) {
            addCriterion("recevier_mobile >=", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileLessThan(String value) {
            addCriterion("recevier_mobile <", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileLessThanOrEqualTo(String value) {
            addCriterion("recevier_mobile <=", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileLike(String value) {
            addCriterion("recevier_mobile like", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileNotLike(String value) {
            addCriterion("recevier_mobile not like", value, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileIn(List<String> values) {
            addCriterion("recevier_mobile in", values, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileNotIn(List<String> values) {
            addCriterion("recevier_mobile not in", values, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileBetween(String value1, String value2) {
            addCriterion("recevier_mobile between", value1, value2, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierMobileNotBetween(String value1, String value2) {
            addCriterion("recevier_mobile not between", value1, value2, "recevierMobile");
            return (Criteria) this;
        }

        public Criteria andRecevierIsNull() {
            addCriterion("recevier is null");
            return (Criteria) this;
        }

        public Criteria andRecevierIsNotNull() {
            addCriterion("recevier is not null");
            return (Criteria) this;
        }

        public Criteria andRecevierEqualTo(String value) {
            addCriterion("recevier =", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierNotEqualTo(String value) {
            addCriterion("recevier <>", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierGreaterThan(String value) {
            addCriterion("recevier >", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierGreaterThanOrEqualTo(String value) {
            addCriterion("recevier >=", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierLessThan(String value) {
            addCriterion("recevier <", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierLessThanOrEqualTo(String value) {
            addCriterion("recevier <=", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierLike(String value) {
            addCriterion("recevier like", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierNotLike(String value) {
            addCriterion("recevier not like", value, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierIn(List<String> values) {
            addCriterion("recevier in", values, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierNotIn(List<String> values) {
            addCriterion("recevier not in", values, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierBetween(String value1, String value2) {
            addCriterion("recevier between", value1, value2, "recevier");
            return (Criteria) this;
        }

        public Criteria andRecevierNotBetween(String value1, String value2) {
            addCriterion("recevier not between", value1, value2, "recevier");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(String value) {
            addCriterion("transaction_id =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(String value) {
            addCriterion("transaction_id <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(String value) {
            addCriterion("transaction_id >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_id >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(String value) {
            addCriterion("transaction_id <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("transaction_id <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLike(String value) {
            addCriterion("transaction_id like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotLike(String value) {
            addCriterion("transaction_id not like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<String> values) {
            addCriterion("transaction_id in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<String> values) {
            addCriterion("transaction_id not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(String value1, String value2) {
            addCriterion("transaction_id between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(String value1, String value2) {
            addCriterion("transaction_id not between", value1, value2, "transactionId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_seckill_order
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 12 23:39:33 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sun Jul 12 23:39:33 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}